package.json, pnpm-lock.yaml, src/connectors/argentMobile/modal/argentModal.ts, src/connectors/webwallet/constants.ts, src/connectors/webwallet/helpers/mapTargetUrlToNodeUrl.ts, src/connectors/webwallet/starknetWindowObject/getWebWalletStarknetObject.ts
=> release 1.0.22

src/main.ts
When opening and closing the modal, a new `div` is created in the `document.body` everytime. This PR fixes this problem.
=> fix: prevent creating multiple root divs

src/main.ts, src/modal/Modal.svelte
usage example:
```css
#starknetkit-modal-container::part(starknetkit-modal){
z-index: 1;
}
```
=> fix: add part attribute for starknetkit modal for css override

src/connectors/argentMobile/modal/argentModal.ts
add `id` for div container for argent mobile modal
this will allow an easier css override if needed
=> fix: add id for argent mobile modal container div

src/connectors/argentMobile/modal/argentModal.ts, src/connectors/argentMobile/modal/login.ts
=> fix: wc params for argent mobile

src/connectors/argentMobile/index.ts
make `inAppBrowserOptions` optional for `ArgentMobileConnector`
`id: argentX` is always passed to the `InjectedConnector` if the context is the in-app argent app browser
=> fix: inAppBrowserOptions as optional

src/connectors/argentMobile/index.ts, src/connectors/webwallet/index.ts
Remove argent mobile and argent webwallet popups when a request is performed (just throw an exception and the dapp will have to manage it)
required for being compatible with starknet-react, since it will always make a request while checking if the connector is connected (and, in this case, it shouldn't open mobile popup login / webwallet)
- remove `this.ensureWallet()` for Argent Mobile connector
- remove `this.ensureWallet()` for Argent Webwallet connector
Please move …
=> fix: remove ensure wallet in argent mobile and argent webwallet 

src/connectors/webwallet/helpers/openWebwallet.ts, src/connectors/webwallet/helpers/trpc.ts, src/connectors/webwallet/index.ts, src/connectors/webwallet/starknetWindowObject/argentStarknetWindowObject.ts
Right now, webwallet performs 2 calls for iframe (requestAccounts and requestChainId) and 3 for a popup (`.authorize` endpoint on trpc).
With this change, everything is done with one call (improving UX).
This change requires a webwallet upgrade too (so this pr will be merged **`after`** webwallet is updated)
- update WebwalletStarknetWindowObject
- update `connect` method on webwallet connector
- remove `authorize` trpc mutation
Please move drafts to the ready for review …
=> feat: upgrade argent webwallet connect with one call

src/hooks/useStarknetkitConnectModal.ts
All properties under `ConnectOptionsWithConnectors` are already optional so, it makes no sense to require options.
Change signature of `useStarknetkitConnectModal`
=> Chore: set `options` as optional in `useStarknetkitConnectModal`

src/hooks/useStarknetkitConnectModal.ts, src/main.ts
Exported methods lack JS docs, it is really helpful for some user so I'm adding them to the functions used externaly
Adding JS Docs to `connect`, `disconnect`, `getSelectedConnectorWallet`, and `useStarknetkitConnectModal`
=> Chore: add jsDocs to exported methods

src/connectors/injected/index.ts
There are two identical interfaces `InjectedConnectorOptions`
- removed duplicate interface `InjectedConnectorOptions`
=> fix: remove duplicate InjectedConnectorOptions

src/connectors/webwallet/helpers/trpc.ts, src/connectors/webwallet/index.ts, src/connectors/webwallet/starknetWindowObject/argentStarknetWindowObject.ts, src/main.ts
=> feat: argent webwallet sso connect

src/connectors/webwallet/helpers/trpc.ts, src/connectors/webwallet/index.ts, src/connectors/webwallet/starknetWindowObject/argentStarknetWindowObject.ts, src/connectors/webwallet/starknetWindowObject/wormhole.ts
Adding `theme` option to webwallet to let developers select `dark` or `light`
`auto` will use the webwallet options
- updated trpc input procedure
=> feat: webwallet connector theme option

.github/workflows/release.yml, src/connectors/webwallet/helpers/trpc.ts
=> fix: webwallet trpc link for popups

package.json, pnpm-lock.yaml, src/connectors/webwallet/helpers/trpc.ts, src/connectors/webwallet/index.ts, src/connectors/webwallet/starknetWindowObject/argentStarknetWindowObject.ts, src/connectors/webwallet/starknetWindowObject/types.ts, src/types/window.ts
=> feat: add webwallet connect and sign method

.github/workflows/release.yml, .releaserc, package.json, pnpm-lock.yaml, src/connectors/argentMobile/index.ts, src/connectors/injected/index.ts, src/connectors/webwallet/index.ts
Update starknetjs version in order to use `WalletAccount` with webwallet connector without requiring
```
const accounts = await this.request({
type: "wallet_requestAccounts",
params: { silent_mode: true },
})
```
- update `starknetjs` and `@starknet-io/types-js`
- use `WalletAccount` instead of `Account`
=> fix: starknetjs version for WalletAccount

src/connectors/webwallet/starknetWindowObject/wormhole.ts
Iframe looks like this right now. Setting the initial height and width fixes this.
=> fix: set initial width and height styles for iframe

src/connectors/webwallet/index.ts
Add missing `ensureWallet` check to request method. Check only if `_wallet` is `undefined`.
=> fix: add missing `ensureWallet` check for web wallet connector

.github/workflows/release.yml, .releaserc, src/connectors/connector.ts, src/connectors/injected/index.ts, src/main.ts
Add connectSilent for `StarknetkitConnector`
- add new method `connectSilent` that uses `silent_mode: true`
- this is used in `connect` in `main.ts` only for argent-x to solve an issue discovered on starkgate
=> fix: connectSilent method for injected connector

src/helpers/publicRcpNodes.ts
Replacing Blast Node URLs with Chainstack, because Blast is sunsetting.
=> fix: replace blast nodes with chainstack (blast is sunsetting)
