argentlabs/starknetkit

src/modal/Modal.svelte
https://github.com/argentlabs/starknetkit/assets/7635032/7a580944-e3e1-418d-b75c-f70f9ab6d7f6
https://github.com/argentlabs/starknetkit/assets/7635032/f8130b8c-a7e3-4297-ae5f-f88396933307
https://github.com/argentlabs/starknetkit/assets/7635032/325bf084-1ad2-4f83-b290-979d78e4693b
https://github.com/argentlabs/starknetkit/assets/7635032/a1e54631-61c3-4f8c-847d-c9991102a700
=> fix: don't show modal if only one connector is defined

src/connectors/argentMobile/modal/argentModal.ts
add id for overlay customization
=> fix: add id for argent mobile modal overlay

src/connectors/argentMobile/index.ts, src/connectors/argentMobile/modal/starknet/adapter.ts
check if session is valid for `isPreauthorized` method in argent mobile connector
=> fix: implement argent mobile connector isPreauthorized method

CONTRIBUTING.md, package.json, src/helpers/mapModalWallets.ts, src/main.ts
- fix: show installed wallets before not installed wallets
- fix reconnect
=> Release 1.1.4 

package.json, pnpm-lock.yaml
=> fix: update starknet-types

.github/workflows/pull-request.yml, .github/workflows/release.yml, pnpm-lock.yaml, src/connectors/argentMobile/modal/starknet/adapter.ts
=> fix: argent mobile invoke transaction backward compatible

src/connectors/webwallet/starknetWindowObject/getWebWalletStarknetObject.ts, src/connectors/webwallet/starknetWindowObject/wormhole.ts
=> fix: add methods to update iframe size

src/connectors/argentMobile/index.ts
dappName property now required for argent mobile connector
=> fix: dappName required for argent mobile connector

src/helpers/defaultConnectors.ts, src/hooks/useStarknetkitConnectModal.ts, src/main.ts, src/window/modal.ts
Fix build error with updated argent mobile params
=> fix: build errors after argent mobile update

package.json, pnpm-lock.yaml, src/connectors/webwallet/helpers/trpc.ts, src/types/window.ts
remove get-starknet-core dep and @argent/x-window
- removed `get-starknet-coreV3`
- removed `@argent/x-window`
- added `x-window` types directly in lib
=> fix: get-starknet-core dependency

src/modal/ConnectorButton.svelte, src/modal/Modal.svelte
=> fix: modal imports

src/connectors/injected/index.ts
Improve DX by adding an explanation to the unobvious emitting of events.
Add comment
=> Improve: Add comment explaining phantom `emits`

src/connectors/argentMobile/index.ts, src/connectors/braavosMobile/index.ts, src/connectors/connector.ts, src/connectors/injected/index.ts, src/connectors/webwallet/index.ts, src/main.ts
=> fix: update connector interface for starknet-react compatibility

.github/workflows/release.yml, .releaserc
=> [HOLD] fix: argent webwallet iframe and backdrop as siblings

src/connectors/webwallet/errors/index.ts, src/connectors/webwallet/helpers/schema.ts, src/connectors/webwallet/helpers/trpc.ts, src/connectors/webwallet/index.ts, src/connectors/webwallet/starknetWindowObject/argentStarknetWindowObject.ts, src/errors/index.ts
=> feat: update sign and approve output and errors

.github/workflows/release.yml, .releaserc, package.json, pnpm-lock.yaml, src/connectors/webwallet/errors/index.ts, src/connectors/webwallet/helpers/schema.ts, src/connectors/webwallet/helpers/trpc.ts, src/connectors/webwallet/index.ts, src/connectors/webwallet/starknetWindowObject/argentStarknetWindowObject.ts, src/connectors/webwallet/starknetWindowObject/types.ts, src/errors/index.ts, src/types/window.ts
Updating `ready` method on the WebWallet connector, so it is persistent.
=> Feat: Updates needed for WW sdk

package.json, pnpm-lock.yaml
=> fix: rollback vite version

src/connectors/webwallet/index.ts
=> fix: update webwallet error messages for connect and sign

src/helpers/mapTargetUrlToNetworkId.ts
=> fix: chain for sepolia iframes

src/connectors/webwallet/index.ts, src/connectors/webwallet/starknetWindowObject/argentStarknetWindowObject.ts
=> fix: add theme option for webwallet connect and sign session

src/connectors/webwallet/helpers/openWebwallet.ts
=> fix: remove ww backdrop to avoid duplicate

package.json, pnpm-lock.yaml
=> fix: update starknetjs version

package.json, pnpm-lock.yaml
=> fix: peer dependencies and x-iu

src/connectors/argent/argentMobile/modal/adapter.ts
Fix a bug in the Argent mobile adapter.
=> fix: fix bug in `isValidSession`
